ci: execute static analysis, fuzzing, and dependency scanner on pull request target
philips-software/amp-embedded-infra-lib pull request #591
Opened 2024-03-19 10:19 UTC by richardapeters

2024-03-20 07:46 UTC, rjaegers approved these changes

2024-03-20 07:47 UTC, rjaegers requested changes
I think the workflows changed in this PR don't actually run in the context of this PR anymore.

2024-06-10 22:22 UTC, daantimmer reviewed
Are we sure we want this?

> `pull_request_target` event grants workflows triggered by pull requests from forks access to repository secrets and a read/write GITHUB_TOKEN. That is inherently risky if the workflow inadvertently exposes these secrets or allows for unauthorized modifications to the repository.
> https://stackoverflow.com/a/74959635

2024-11-11 12:36 UTC, closed without merging

2024-11-11 12:36 UTC, rjaegers commented
Handling of forks will need a different solution.